spring:
  application:
    name: config-client
  cloud:
    zookeeper:
      enabled: false
server:
  port: 8081

eureka:
  client:
    enabled: false
---
spring:
  profiles: eureka
#eureka 配置客户端
eureka:
  server:
    host: 127.0.0.1
    port: 8888
  client:
    serviceUrl:
      defaultZone: http://${eureka.server.host}:${eureka.server.port}/eureka
    enabled: true
---
spring:
  profiles: zookeeper
  cloud:
      zookeeper:
        connectString: 192.168.244.138:2181
        enabled: true

---
spring:
  cloud:
    consul:
      discovery:
        enabled: false