spring:
  application:
    name: config-client
server:
  port: 8081

#eureka 配置客户端
eureka:
  server:
    host: 127.0.0.1
    port: 8888
  client:
    serviceUrl:
      defaultZone: http://${eureka.server.host}:${eureka.server.port}/eureka
